steps:
  # Build the real-agent-api Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/analyst/real-agent-api:latest', '-f', 'Dockerfile', '.']
    dir: 'agents-python/server'

  # Push the real-agent-api Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/analyst/real-agent-api:latest']

  # Deploy the real-agent-api to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'real-agent-api'
      - '--image=us-central1-docker.pkg.dev/${PROJECT_ID}/analyst/real-agent-api:latest'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=4Gi'
      - '--cpu=2'
      - '--timeout=3600s'
      - '--max-instances=10'

images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/analyst/real-agent-api:latest'

timeout: '3600s'
