version: "3.8"

services:
  startup-analyst:
    build:
      context: ..
      dockerfile: docker/Dockerfile.startup-analyst
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/service-account.json
    volumes:
      - ../credentials:/app/credentials
    restart: unless-stopped

  startup-chatbot:
    build:
      context: ..
      dockerfile: docker/Dockerfile.startup-chatbot
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/service-account.json
    volumes:
      - ../credentials:/app/credentials
      - ../Startup-Analyst/outputs/notes:/app/notes
    restart: unless-stopped
    depends_on:
      - startup-analyst
